default: &default
  adapter: sqlite3
  database: db/ohmydog.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/ohmydog_development.sqlite3

test:
  <<: *default
  database: db/ohmydog_test.sqlite3

production:
  <<: *default
  database: db/ohmydog_production.sqlite3
